theme: jekyll-theme-cayman

title: GRIN Compiler
description: whole program optimizer for lazy and strict functional languages

show_downloads: false
google_analytics:

github: [metadata]

grin:
  repository_url: https://github.com/grin-tech/grin
  patreon_url: https://www.patreon.com/csaba_hruska
